# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Curtis Larson's Blog
tagline:          A lot of software talk.
url:              http://curtismlarson.com/blog
paginate:         1
baseurl:          http://quackware.github.io/blog/
# dev url
#baseurl: /
author:
  name:           Curtis Larson
  url:            https://twitter.com/quackware
  email:          curtis@curtismlarson.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/quackware/blog

pages_list:
  Home: '/'
  About: './about'
  Archive: './archive'
  Feed: './atom.xml'

highlighter: true